CREATE TABLE IF NOT EXISTS SuperAdmin(
   ID SERIAL PRIMARY KEY NOT NULL,
   nom VARCHAR(50) NOT NULL,
   prenom VARCHAR(50) NOT NULL,
   email VARCHAR(50) NOT NULL,
   password TEXT NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Centre(
   id_centre SERIAL PRIMARY KEY NOT NULL,
   nom_centre VARCHAR(50) NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Admin(
   ID SERIAL PRIMARY KEY NOT NULL,
   nom VARCHAR(50) NOT NULL,
   prenom VARCHAR(50) NOT NULL,
   email VARCHAR(50) NOT NULL,
   password TEXT NOT NULL,
   centre_id INTEGER REFERENCES Centre (id_centre) ON UPDATE CASCADE ON DELETE CASCADE,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Categorie(
   id_categorie SERIAL PRIMARY KEY NOT NULL,
   nom_categorie VARCHAR(50) NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Responsaple_Rayon(
   ID SERIAL PRIMARY KEY NOT NULL,
   nom VARCHAR(50) NOT NULL,
   prenom VARCHAR(50) NOT NULL,
   email VARCHAR(50) NOT NULL,
   password TEXT NOT NULL,
   categorie_id INTEGER REFERENCES Categorie (id_categorie) ON UPDATE CASCADE ON DELETE CASCADE,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Produit(
   id_produit SERIAL PRIMARY KEY NOT NULL,
   nom_produit VARCHAR(50) NOT NULL,
   quantite INTEGER NOT NULL,
   prix DECIMAL NOT NULL,
   categorie_id INTEGER REFERENCES Categorie (id_categorie) ON UPDATE CASCADE ON DELETE CASCADE,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Promotion(
   ID SERIAL PRIMARY KEY NOT NULL,
   pourcentage DECIMAL NOT NULL, 
   produit_id INTEGER REFERENCES Produit(id_produit) ON UPDATE CASCADE ON DELETE CASCADE,
   categorie_id INTEGER REFERENCES Categorie (id_categorie) ON UPDATE CASCADE ON DELETE CASCADE,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
